policy:
  students:
    max_shifts: 2
appearance:
  badges:
    spots_count_thresholds:
      inverse: 0
      important: 1
      warning: 4
      info: 8
      success: 10
    quota_remaining_thresholds:
      info: 1
      success: 2
phases:
  pre:
    notice: System ready.
    start_date: 2013-01-01 00:00:00 -5
    end_date: 2013-01-18 23:59:59 -5
    who_can_signup: No one
    after_phase: seniors/PGs will be able to sign up
    graduation_years: []
  seniors:
    notice: Seniors/PGs only today!
    start_date: 2013-01-19 00:00:00 -5
    end_date: 2013-01-19 23:59:59 -5
    who_can_signup: Only seniors
    after_phase: everyone can sign up
    graduation_years: [13]
  everyone:
    notice: Sign up now!
    start_date: 2013-01-20 00:00:00 -5
    end_date: 2013-01-22 23:59:59 -5
    who_can_signup: Everyone
    after_phase: no one will be allowed to make any changes
    graduation_years: [13,14,15,16]
  freeze:
    notice: Sign up ended.
    start_date: 2013-01-23 00:00:00 -5
    end_date: 2013-01-31 23:59:59 -5
    who_can_signup: No one
    after_phase: it is Feburary
    graduation_years: []
